[theme]
theme = "gruvbox-dark"
[icons]
icons = "awesome6"


[[block]]
block = "cpu"


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
interval = 30
warning_mem = 70
critical_mem = 90
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = " $icon  $percentage "


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
